---
- name: My test play
  hosts: virtuals
  become: true
  tasks:
    - name: create user cloudru
      user:
        name: cloudru
        password: "{{ 'cloudpass' | password_hash('sha512', 'SomeSalt') }}"
        shell: /bin/bash

    - name: enable ssh keys
      blockinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        block: |
          PasswordAuthentication no
          PermitRootLogin no
        create: true

    - name: copy ssh key
      blockinfile:
        path: /home/cloudru/.ssh/authorized_keys
        block: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfrfE0OluoNHb5dOpV4RpWmVXvMBWc17kaM7DDjCm7romNQMDX95i5Fc67Q3c47pvrm/qi/ZqsCeqNdLl5+VV41rVz701Pj/UUr2FZpIm80Ur0iM1DFy81GKo/lS1INopqdd4KvUnM2d8yqfJSm9m5Cq7AM9S0mqObuMayfqNR4YcOlm9fnEMqhrSWbBVvdghPNiBzs7T9RzEq/0w8rs743tCF7MICv72fdgYadrGlxFsFWSujwZXQLI4VUSxKirJBCUgfR0u84gZK/wUzJ4EPqMichniTf24AsvidozUHWMDmQ+pUaBTyxjD5egi8LcV0EHH4feHwzacA2gyGbOtFK3wpa/dgE1yvPTkPKnccIXKnbel0mfxfsBVkclc5/DnczmrdaGrX5DCrQbI+HO4lhr4KzAm/pw6qfLcw8KjCdVKsnCRXykdat8KUwNAeolknRWdKDqdsbyXBj+ePMTlMR8YmoBj9znYWwOnAAyu56utiteL0oq9YPkb7ZGF5ZOE="
        create: true
        owner: cloudru

    - name: reload sshd unit
      systemd:
        name: sshd
        state: restarted
